"""add-tables-post-publish

Revision ID: d2a605a087be
Revises: d71f09e5469b
Create Date: 2022-02-27 17:13:49.424833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a605a087be'
down_revision = 'd71f09e5469b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
